FROM alpine:edge AS build
RUN apk add --no-cache \
    crystal \
    shards \
    gc-dev \
    gc-static \
    pcre2-dev \
    pcre2-static \
    yaml-dev \
    yaml-static \
    openssl-dev \
    openssl-libs-static \
    libxml2-dev \
    libxml2-static \
    zlib-dev \
    zlib-static \
    xz-dev \
    xz-static

COPY . /app

RUN cd /app \
    && shards build --static --release \
    && strip bin/grafito

FROM scratch
COPY --from=build /app/bin/grafito /
